NODE_META = [
    {
        "id": "schema",
        "step": 1,
        "name": "Schema 设计",
        "subtitle": "6 类实体 · 9 类关系",
        "phase": "A",
        "module": "app.pipeline.nodes.s1_schema",
        "desc": "从异常归因业务问题出发定义领域本体，自顶向下 + 语料校准，版本化落盘",
        "outputs": [
            "ontology.yaml（实体/关系/属性/定义域值域/约束）",
            "Schema 版本记录（SQLite）",
        ],
    },
    {
        "id": "corpus",
        "step": 2,
        "name": "语料构建",
        "subtitle": "约 200 份多体裁文档",
        "phase": "A",
        "module": "app.pipeline.nodes.s2_corpus",
        "desc": "种子知识库 + 模板渲染生成 SOP/异常记录/工艺通知单，注入真实噪声并自带金标准",
        "outputs": [
            "data/corpus/*.txt（约 200 份）",
            "data/gold/corpus_gold.jsonl（每文档隐藏三元组金标）",
        ],
    },
    {
        "id": "extract",
        "step": 3,
        "name": "LLM 结构化抽取",
        "subtitle": "实体 / 关系 / 属性",
        "phase": "A",
        "module": "app.pipeline.nodes.s3_extract",
        "desc": "Schema 注入 + few-shot + JSON mode；支持 DeepSeek 与 mock 规则抽取，带缓存与断点续跑",
        "outputs": [
            "outputs/entities.jsonl",
            "outputs/relations.jsonl",
            "300 条随机抽检集（data/gold/sample300.jsonl）",
        ],
    },
    {
        "id": "align",
        "step": 4,
        "name": "后处理与实体对齐",
        "subtitle": "别名归一 + embedding 阈值",
        "phase": "A",
        "module": "app.pipeline.nodes.s4_align",
        "desc": "别名表归一、单位标准化；别名精确命中优先，未命中走 embedding 相似度聚类",
        "outputs": [
            "outputs/entities_aligned.jsonl",
            "outputs/relations_aligned.jsonl",
            "合并审计日志、重复实体率/孤立节点率",
        ],
    },
    {
        "id": "ingest",
        "step": 5,
        "name": "Neo4j 入图",
        "subtitle": "约束 / 索引 / 幂等写入",
        "phase": "A",
        "module": "app.pipeline.nodes.s5_ingest",
        "desc": "MERGE 幂等写入 Neo4j（不可用时写内存图库），建唯一约束与向量索引，校验规模",
        "outputs": [
            "图数据库节点/关系真实统计",
            "Cypher 多跳归因查询模板",
        ],
    },
    {
        "id": "index",
        "step": 6,
        "name": "双路索引构建",
        "subtitle": "BM25 + 向量索引",
        "phase": "B",
        "module": "app.pipeline.nodes.s6_index",
        "desc": "文档块关联实体偏移，rank_bm25 建倒排，embedding + faiss 建向量索引",
        "outputs": ["index/bm25.pkl", "index/faiss.index", "outputs/chunks.jsonl"],
    },
    {
        "id": "retrieve",
        "step": 7,
        "name": "三路检索",
        "subtitle": "BM25 · 向量RAG · GraphRAG",
        "phase": "B",
        "module": "app.pipeline.nodes.s7_retrieve",
        "desc": "实体链接 → Cypher 多跳子图召回 → 三元组转文本上下文；三路全程留痕",
        "outputs": ["outputs/retrieval_trace.jsonl（每题三路命中明细）"],
    },
    {
        "id": "qa",
        "step": 8,
        "name": "多跳归因问答",
        "subtitle": "现象 → 原因 → 对策 → 工序",
        "phase": "B",
        "module": "app.pipeline.nodes.s8_qa",
        "desc": "向量（开放语义）+ 图谱（关系推理）双路融合生成答案，附证据与子图路径",
        "outputs": ["outputs/qa_answers.jsonl"],
    },
    {
        "id": "evaluate",
        "step": 9,
        "name": "评测与消融",
        "subtitle": "F1 · Hit@3 · 准确率",
        "phase": "C",
        "module": "app.pipeline.nodes.s9_evaluate",
        "desc": "300 条抽检算抽取 P/R/F1；150 题（单跳/多跳/聚合）算 Hit@3/MRR/准确率；消融图谱通道",
        "outputs": [
            "eval/metrics_summary.json",
            "eval/per_question.csv（逐题判分明细）",
        ],
    },
]

NODE_INDEX = {n["id"]: n for n in NODE_META}
